### ISSUE TITLE
RFC: Function arguments

### ISSUE THREAD

**Issue by ollef** [llvm-hs/llvm-irbuilder#3]
The type of `function` is:

```
function
  :: Name                  -- ^ Function name
  -> [(Type, Name)]        -- ^ Parameters (non-variadic)
  -> Type                  -- ^ Return type
  -> ([Operand] -> IRBuilder Function ()) -- ^ Function generation
  -> IRBuilder Toplevel Operand
```

This means that the "Function generation"/body builder argument is passed operands for the arguments, which means you can use it as follows:

```
function "baz" [(double, "arg")] double $ \[arg] -> ...
```

Note the `arg` which is an `Operand` for the `double` argument that can be used when defining the body.

An alternative formulation would be to not do this and let the user construct the operands manually.

The benefit of doing this is that small examples become more elegant, but I somehow doubt this makes much of a difference in actual compiler backends. The functionality is also trivial to reconstruct if necessary.

Opinions?

**Comment by sdiehl** [comment]
When generating the IR programmatically as part of a real compiler it's doubtful we'd actually want to use the operands as function argument since it's usually part of larger codegen mechanism that's reading from some state / reader for the arguments.

However it is nice for simple examples and perhaps the Kaleidoscope tutorial. Is there any reason we couldn't just have two emitters for function generation though?

**Comment by ollef** [comment]
Two functions sounds like the way to go. Thanks @sdiehl!

**Comment by ollef** [comment]
This has been solved, so closing. :)
